Importando a biblioteca pandas e lendo o arquivo csv com os dados
sobre o projeto do café

In [8]:
import pandas as pd

df = pd.read_csv("dirty_cafe_sales.csv")

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

Verificando a existencia de valores nulos, como de primeira visualização já percebe
que existem

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

Realizando de forma descritiva os dados que estão no dataframe com describe()

In [9]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

Verificando se existem linhas duplicadas

In [14]:
df.duplicated().sum()

np.int64(0)

Verificando os tipos de dados que tem no dataset

In [16]:
df.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

Verificando o por que existem tipos de dados que deveriam ser outro estão todos string

In [17]:
for col in ["Quantity", "Price Per Unit", "Total Spent", "Transaction Date"]:
    print(col, df[col].unique()[:20])

Quantity <StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str
Price Per Unit <StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str
Total Spent <StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str
Transaction Date <StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 '2023-11-07',      'ERROR', '2023-05-03', '2023-06-01', '2023-03-21',
 '2023-11-15', '2023-06-10', '2023-02-24', '2023-03-25', '2023-01-15']
Length: 20, dtype: str

Transformando os tipos de dados por terem dados que são numéricos e estão como
string e data, pois existem valores como "error", "unknown" que fazendo com que
o pandas identifique como str

In [ ]:
cols_num = ["Quantity", "Price Per Unit", "Total Spent"]
df[cols_num] = df[cols_num].apply(pd.to_numeric, errors="coerce")
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors="coerce")
df.dtypes

Transaction ID                 str
Item                           str
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

Coluna Transaction Date, contem valor 'NaT' após a transformação dos tipos de dados das tabelas

In [40]:
for col in ["Quantity", "Price Per Unit", "Total Spent", "Transaction Date"]:
    print(col, df[col].unique()[:20])

Quantity [ 2.  4.  5.  3.  1. nan]
Price Per Unit [2.  3.  1.  5.  4.  1.5 nan]
Total Spent [ 4.  12.   nan 10.  20.   9.  16.  15.  25.   8.   5.   3.   6.   2.
  1.   7.5  4.5  1.5]
Transaction Date <DatetimeArray>
['2023-09-08 00:00:00', '2023-05-16 00:00:00', '2023-07-19 00:00:00',
 '2023-04-27 00:00:00', '2023-06-11 00:00:00', '2023-03-31 00:00:00',
 '2023-10-06 00:00:00', '2023-10-28 00:00:00', '2023-07-28 00:00:00',
 '2023-12-31 00:00:00', '2023-11-07 00:00:00',                 'NaT',
 '2023-05-03 00:00:00', '2023-06-01 00:00:00', '2023-03-21 00:00:00',
 '2023-11-15 00:00:00', '2023-06-10 00:00:00', '2023-02-24 00:00:00',
 '2023-03-25 00:00:00', '2023-01-15 00:00:00']
Length: 20, dtype: datetime64[us]

Realizando a verificação de quantos valores nulos existem

In [29]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [58]:
for col in ["Item", "Payment Method", "Location"]:
    print(col, df[col].unique())

Item <StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',        nan,
 'Sandwich',    'Juice',      'Tea']
Length: 9, dtype: str
Payment Method <StringArray>
['Credit Card', 'Cash', nan, 'Digital Wallet']
Length: 4, dtype: str
Location <StringArray>
['Takeaway', 'In-store', nan]
Length: 3, dtype: str

Verificado que colunas de texto contem dados com error e unknown tendo que transformar
em nan utilizando a biblioteca numpy para transformar esses textos

In [46]:
import numpy as np
cols_txt = ["Item", "Payment Method", "Location"]
df[cols_txt] = df[cols_txt].replace(["ERROR", "UNKNOWN"], np.nan)

In [63]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
#Data tratada sem NAT para realizar verificações mais detalhadas
df_datas = df.dropna(subset=["Transaction Date"]) 
df_datas.groupby(df_datas["Transaction Date"].dt.month)["Total Spent"].sum()
len(df_datas)

9540

Verificar os valores nulos após os tratamentos dos dados para tipo nan

In [64]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [ ]:
preco_item = df.groupby("Item")["Price Per Unit"]